version: '3.6'

services:

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch1
    hostname: elasticsearch1
    restart: unless-stopped
    volumes:
      - type: volume
        source: es1_data
        target: /usr/share/elasticsearch/data
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment:
      - "node.name=elasticsearch1"
      - "bootstrap.memory_lock=true"
      - "cluster.name=es-cluster"
      - "discovery.seed_hosts=elasticsearch2,elasticsearch3,elasticsearch1"
      - "cluster.initial_master_nodes=elasticsearch2,elasticsearch3,elasticsearch1"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.index.number_of_replicas=0"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "xpack.ml.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.watcher.enabled=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 10
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1500m

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch2
    hostname: elasticsearch2
    restart: unless-stopped
    volumes:
      - type: volume
        source: es2_data
        target: /usr/share/elasticsearch/data
    ports: 
      - "9201:9200"
      - "9301:9300"
    environment:
      - "node.name=elasticsearch2"
      - "bootstrap.memory_lock=true"
      - "cluster.name=es-cluster"
      - "discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3"
      - "cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.index.number_of_replicas=0"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "xpack.ml.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.watcher.enabled=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 10
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1500m

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch3
    hostname: elasticsearch3
    restart: unless-stopped
    volumes:
      - type: volume
        source: es3_data
        target: /usr/share/elasticsearch/data
    ports: 
      - "9202:9200"
      - "9302:9300"
    environment:
      - "node.name=elasticsearch3"
      - "bootstrap.memory_lock=true"
      - "cluster.name=es-cluster"
      - "discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3"
      - "cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.index.number_of_replicas=0"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "xpack.ml.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.watcher.enabled=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 10
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1500m

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    restart: unless-stopped
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch1:9200"
      - "SERVER_NAME=localhost"
      - "XPACK_MONITORING_ENABLED=false"
    ports:
      - "5601:5601"

  es-writer:
    build: es-writer
    container_name: es-writer
    restart: unless-stopped
    environment:
      - "ES_HOST_SEED=elasticsearch1,elasticsearch2,elasticsearch3"

  es-reader:
    build: es-reader
    container_name: es-reader
    restart: unless-stopped 
    environment:
      - "ES_HOST_SEED=elasticsearch3,elasticsearch2,elasticsearch1"

  logstash-ingest:
    build: ./logstash-ingest
    container_name: logstash-ingest
    restart: "no"
    volumes:
      - type: bind
        source: ./logstash-ingest/data
        target: /data
    deploy:
      resources:
        limits:
          memory: 500m

  filebeat-ingest:
    build: ./filebeat-ingest
    container_name: filebeat-ingest
    restart: "no"
    volumes:
      - type: bind
        source: ./filebeat-ingest/data
        target: /data
    deploy:
      resources:
        limits:
          memory: 500m

volumes:
  es1_data:
  es2_data:
  es3_data:
